#ifndef MALE_MUSCLED_H
#define MALE_MUSCLED_H

#include "../actor/actor.h"

#define male_muscled_model "rom:/models/male_muscled.t3dm"
#define gorilla_model "rom:/models/gorilla.t3dm"

// motion settings

#define MALE_MUSCLED_IDLE_ACCELERATION_RATE 8.0f
#define MALE_MUSCLED_WALK_ACCELERATION_RATE 3.0f
#define MALE_MUSCLED_RUN_ACCELERATION_RATE 5.0f
#define MALE_MUSCLED_SPRINT_ACCELERATION_RATE 8.0f
#define MALE_MUSCLED_ROLL_ACCELERATION_GRIP_RATE 2.0f

#define MALE_MUSCLED_STAND_ROLL_TARGET_SPEED 300.0f
#define MALE_MUSCLED_STAND_ROLL_LAUNCH_RATE 15.0f
#define MALE_MUSCLED_WALK_ROLL_TARGET_SPEED 300.0f
#define MALE_MUSCLED_WALK_ROLL_LAUNCH_RATE 15.0f
#define MALE_MUSCLED_RUN_ROLL_TARGET_SPEED 468.0f
#define MALE_MUSCLED_RUN_ROLL_LAUNCH_RATE 15.0f
#define MALE_MUSCLED_SPRINT_ROLL_TARGET_SPEED 624.0f
#define MALE_MUSCLED_SPRINT_ROLL_LAUNCH_RATE 15.0f

#define MALE_MUSCLED_AERIAL_CONTROL_RATE 0.5f

#define MALE_MUSCLED_WALK_TARGET_SPEED 180.0f
#define MALE_MUSCLED_RUN_TARGET_SPEED 390.0f
#define MALE_MUSCLED_SPRINT_TARGET_SPEED 520.0f

#define MALE_MUSCLED_JUMP_FORCE_MULTIPLIER 3000
#define MALE_MUSCLED_JUMP_MINIMUM_SPEED 500

#define MALE_MUSCLED_GRAVITY -1800
#define MALE_MUSCLED_FALL_MAX_SPEED 1000


// convertion ratio between locomotion animation lengths

#define MALE_MUSCLED_RUN_TO_WALK_RATIO 1.347826f
#define MALE_MUSCLED_WALK_TO_RUN_RATIO 0.741935f

#define MALE_MUSCLED_SPRINT_TO_RUN_RATIO 1.15f
#define MALE_MUSCLED_RUN_TO_SPRINT_RATIO 0.869565f

#define MALE_MUSCLED_SPRINT_TO_WALK_RATIO 1.55f
#define MALE_MUSCLED_WALK_TO_SPRINT_RATIO 0.645161f


// animation lengths in seconds

#define MALE_MUSCLED_ACTION_IDLE_MAX_BLENDING_RATIO 0.85f

#define MALE_MUSCLED_WALKING_ANIM_LENGTH 1.033333f
#define MALE_MUSCLED_WALKING_ANIM_LENGTH_HALF 0.516666f

#define MALE_MUSCLED_RUNNING_ANIM_LENGTH_HALF 0.4f
#define MALE_MUSCLED_RUNNING_ANIM_LENGTH 0.766666f

#define MALE_MUSCLED_SPRINTING_ANIM_LENGTH 0.666666f
#define MALE_MUSCLED_SPRINTING_ANIM_LENGTH_HALF 0.333333f

#define MALE_MUSCLED_RUN_TO_ROLLING_ANIM_GROUND 0.3f
#define MALE_MUSCLED_RUN_TO_ROLLING_ANIM_GRIP 0.9f
#define MALE_MUSCLED_RUN_TO_ROLLING_ANIM_STAND 0.9f
#define MALE_MUSCLED_RUN_TO_ROLLING_ANIM_LENGTH 1.166666f

#define MALE_MUSCLED_STAND_TO_ROLLING_ANIM_GROUND 0.533333f
#define MALE_MUSCLED_STAND_TO_ROLLING_ANIM_GRIP 1.166666f
#define MALE_MUSCLED_STAND_TO_ROLLING_ANIM_STAND 1.166666f
#define MALE_MUSCLED_STAND_TO_ROLLING_ANIM_LENGTH 1.5f

#define MALE_MUSCLED_JUMP_ANIM_LENGTH 0.633333f
#define MALE_MUSCLED_JUMP_ANIM_CROUCH 0.1f
#define MALE_MUSCLED_JUMP_ANIM_AIR 0.233333f
#define MALE_MUSCLED_JUMP_MAX_BLENDING_RATIO 0.55f
#define MALE_MUSCLED_JUMP_FOOTING_SPEED 0.4f

#define MALE_MUSCLED_LAND_ANIM_LENGTH 0.9f
#define MALE_MUSCLED_LAND_ANIM_GROUND 0.266666f
#define MALE_MUSCLED_LAND_ANIM_CROUCH 0.5f
#define MALE_MUSCLED_LAND_ANIM_STAND 0.833333f


// --- Slots ---

typedef enum {
    MM_SLOT_IDLE_R,
    MM_SLOT_WALK,
    MM_SLOT_RUN,
    MM_SLOT_SPRINT,
    MM_SLOT_TURN_WALK,
    MM_SLOT_TURN_RUN,
    MM_SLOT_JUMP_L,
    MM_SLOT_JUMP_R,
    MM_SLOT_LAND_L,
    MM_SLOT_LAND_R,
    MM_SLOT_ROLL_RUN,
    MM_SLOT_ROLL_STAND,
    MM_SLOT_TRANSITION,
    MM_SLOT_COUNT
} MaleMuscledSlot;


// --- Animations ---

typedef enum {

    MM_ANIM_IDLE_L,
    MM_ANIM_IDLE_R,

    MM_ANIM_STAND_TO_WALK_L,
    MM_ANIM_STAND_TO_WALK_R,

    MM_ANIM_STAND_TO_RUN_L,
    MM_ANIM_STAND_TO_RUN_R,

    MM_ANIM_WALK,
    MM_ANIM_TURN_WALK_L,
    MM_ANIM_TURN_WALK_R,
    MM_ANIM_WALK_CHANGE_DIR_L,
    MM_ANIM_WALK_CHANGE_DIR_R,
    MM_ANIM_WALK_TO_STAND_L,
    MM_ANIM_WALK_TO_STAND_R,

    MM_ANIM_WALK_BACK,
    MM_ANIM_WALK_BACK_L,
    MM_ANIM_WALK_BACK_R,
    MM_ANIM_WALK_STRAFE_L,
    MM_ANIM_WALK_STRAFE_R,

    MM_ANIM_RUN,
    MM_ANIM_TURN_RUN_L,
    MM_ANIM_TURN_RUN_R,
    MM_ANIM_RUN_CHANGE_DIR_L,
    MM_ANIM_RUN_CHANGE_DIR_R,
    MM_ANIM_RUN_TO_STAND_L,
    MM_ANIM_RUN_TO_STAND_R,

    MM_ANIM_RUN_BACK,
    MM_ANIM_RUN_BACK_L,
    MM_ANIM_RUN_BACK_R,
    MM_ANIM_RUN_STRAFE_L,
    MM_ANIM_RUN_STRAFE_R,

    MM_ANIM_SPRINT,

    MM_ANIM_JUMP_L,
    MM_ANIM_JUMP_R,
    MM_ANIM_FALL_L,
    MM_ANIM_FALL_R,
    MM_ANIM_LAND_L,
    MM_ANIM_LAND_R,

    MM_ANIM_ROLL_L,
    MM_ANIM_ROLL_R,
    MM_ANIM_STAND_ROLL_L,
    MM_ANIM_STAND_ROLL_R,

    MM_ANIM_SLIDE_L,
    MM_ANIM_SLIDE_R,

    MM_ANIM_TRANSITION_L,
    MM_ANIM_TRANSITION_R,

    MM_ANIM_COUNT
    
} MaleMuscledAnim;


extern const ActorMotionSettings    male_muscled_motion_settings;
extern const ActorAnimationSettings male_muscled_animation_settings;
extern const AnimDef                male_muscled_anim_def;

#endif
